### PR TITLE
cicd test

### PR DESCRIPTION
**Pull request by animationzl**

### CODE REVIEW

**Comment by mrhillsman** [comment]
Build failed.

- terraform-openstack-unittest http://80.158.20.68/logs/1/1/b3df2eae0111ba9e18bd1578d9b67b0450e14011/check/terraform-openstack-unittest/390ee30/ : FAILURE in 34s
- terraform-openstack-acctest terraform-openstack-acctest : ERROR Unable to find playbook /var/lib/zuul/builds/4c74e9ce57334328a5600f21ee88714f/trusted/project_2/github.com/theopenlab/openlab-zuul-jobs/playbooks/acctest/run

**Comment by animationzl** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-openstack-unittest terraform-openstack-unittest : NODE_FAILURE
- terraform-openstack-acctest terraform-openstack-acctest : NODE_FAILURE

**Comment by animationzl** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-openstack-unittest http://80.158.20.68/logs/1/1/b3df2eae0111ba9e18bd1578d9b67b0450e14011/check/terraform-openstack-unittest/61c598e/ : SUCCESS in 51s
- terraform-openstack-acctest http://80.158.20.68/logs/1/1/b3df2eae0111ba9e18bd1578d9b67b0450e14011/check/terraform-openstack-acctest/318d998/ : FAILURE in 25m 27s

**Pull request closed without merging**
