### PR TITLE
Support separate FWaaS tests for terraform-openstack-provider

### PR DESCRIPTION
**Pull request by kiwik**
Associate FWaaS job with terraform-openstack-provider project

Fixes: https://github.com/theopenlab/openlab-zuul-jobs/issues/35

Part of https://github.com/orgs/theopenlab/projects/1#card-6800912

### CODE REVIEW

**Comment by kiwik** [comment]
Please recheck PR until theopenlab/project-config and theopenlab/zuul-jobs related FWaaS job defination merged.

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by animationzl** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
OpenLab side logic have done, test fails should be addressed in SDK/Tools or OpenStack side.

**Pull request merged**
