### PR TITLE
Call only acc test on master OpenStack

### PR DESCRIPTION
**Pull request by liu-sheng**
Call only acc test on master OpenStack

### CODE REVIEW

**Comment by mrhillsman** [comment]
Build failed.

- terraform-provider-openstack-acceptance-test terraform-provider-openstack-acceptance-test : NODE_FAILURE

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-provider-openstack-acceptance-test http://80.158.20.68/logs/5/5/0b86b20372905c8d86702069102e76229e92e759/check/terraform-provider-openstack-acceptance-test/2e9b74c/ : FAILURE in 28m 31s

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-provider-openstack-acceptance-test http://80.158.20.68/logs/5/5/0b86b20372905c8d86702069102e76229e92e759/check/terraform-provider-openstack-acceptance-test/56bd1ee/ : FAILURE in 2h 28m 10s

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-provider-openstack-acceptance-test http://80.158.20.68/logs/5/5/0b86b20372905c8d86702069102e76229e92e759/check/terraform-provider-openstack-acceptance-test/82783fd/ : POST_FAILURE in 2h 28m 01s

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-provider-openstack-acceptance-test http://80.158.20.68/logs/5/5/0b86b20372905c8d86702069102e76229e92e759/check/terraform-provider-openstack-acceptance-test/1b2d5ef/ : FAILURE in 1h 45m 34s

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-provider-openstack-acceptance-test http://80.158.20.68/logs/5/5/0b86b20372905c8d86702069102e76229e92e759/check/terraform-provider-openstack-acceptance-test/c3323bc/ : FAILURE in 2h 28m 05s

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-provider-openstack-acceptance-test http://80.158.20.68/logs/5/5/0b86b20372905c8d86702069102e76229e92e759/check/terraform-provider-openstack-acceptance-test/1f4bf44/ : FAILURE in 2h 27m 58s

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- terraform-provider-openstack-acceptance-test http://80.158.20.68/logs/5/5/0b86b20372905c8d86702069102e76229e92e759/check/terraform-provider-openstack-acceptance-test/046ecd8/ : TIMED_OUT in 3h 27m 41s

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by kiwik** [comment]
Close the test PR.

**Pull request closed without merging**
